[package]
name = "egui_btleplug_example"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.6"
egui = "0.29.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.41", features = ["rt", "macros", "rt-multi-thread"] }
